# TODO a cosa servono
# - group-id, auto-offset-reset

server:
  port: 9000
spring:
  kafka:
    properties:
      auto.register.schemas: false
      use.latest.version: true
      schema:
        registry:
          url: http://localhost:8081
          basic.auth.user.info:
      basic.auth.credentials.source:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: patient-location
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    streams:
      application-id: LocationService
      properties:
        default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
        default.value-deserializer: io.confluent.kafka.streams.serdes.avro.GenericAvroDeserializer
        default.value-serializer: io.confluent.kafka.streams.serdes.avro.SpecificAvroSerializer
# debug: true

