/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ch.demo.gpietro.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventPatientLocation extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 8061636555619552911L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventPatientLocation\",\"namespace\":\"ch.demo.gpietro.schema\",\"fields\":[{\"name\":\"patientId\",\"type\":\"long\"},{\"name\":\"episodeOfCareId\",\"type\":\"long\"},{\"name\":\"wardId\",\"type\":\"long\"},{\"name\":\"roomId\",\"type\":\"long\"},{\"name\":\"bedId\",\"type\":\"long\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"EncounterStatus\",\"symbols\":[\"PAST\",\"ACTIVE\",\"PLANNED\"]},\"doc\":\"Encounter status\"},{\"name\":\"date\",\"type\":[\"null\",{\"type\":\"long\",\"connect.version\":1,\"connect.name\":\"org.apache.kafka.connect.data.Timestamp\",\"logicalType\":\"timestamp-millis\"}]}],\"version\":\"1\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<EventPatientLocation> ENCODER =
      new BinaryMessageEncoder<EventPatientLocation>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<EventPatientLocation> DECODER =
      new BinaryMessageDecoder<EventPatientLocation>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<EventPatientLocation> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<EventPatientLocation> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<EventPatientLocation> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<EventPatientLocation>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this EventPatientLocation to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a EventPatientLocation from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a EventPatientLocation instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static EventPatientLocation fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private long patientId;
   private long episodeOfCareId;
   private long wardId;
   private long roomId;
   private long bedId;
  /** Encounter status */
   private ch.demo.gpietro.schema.EncounterStatus status;
   private java.time.Instant date;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public EventPatientLocation() {}

  /**
   * All-args constructor.
   * @param patientId The new value for patientId
   * @param episodeOfCareId The new value for episodeOfCareId
   * @param wardId The new value for wardId
   * @param roomId The new value for roomId
   * @param bedId The new value for bedId
   * @param status Encounter status
   * @param date The new value for date
   */
  public EventPatientLocation(java.lang.Long patientId, java.lang.Long episodeOfCareId, java.lang.Long wardId, java.lang.Long roomId, java.lang.Long bedId, ch.demo.gpietro.schema.EncounterStatus status, java.time.Instant date) {
    this.patientId = patientId;
    this.episodeOfCareId = episodeOfCareId;
    this.wardId = wardId;
    this.roomId = roomId;
    this.bedId = bedId;
    this.status = status;
    this.date = date;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return patientId;
    case 1: return episodeOfCareId;
    case 2: return wardId;
    case 3: return roomId;
    case 4: return bedId;
    case 5: return status;
    case 6: return date;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: patientId = (java.lang.Long)value$; break;
    case 1: episodeOfCareId = (java.lang.Long)value$; break;
    case 2: wardId = (java.lang.Long)value$; break;
    case 3: roomId = (java.lang.Long)value$; break;
    case 4: bedId = (java.lang.Long)value$; break;
    case 5: status = (ch.demo.gpietro.schema.EncounterStatus)value$; break;
    case 6: date = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'patientId' field.
   * @return The value of the 'patientId' field.
   */
  public long getPatientId() {
    return patientId;
  }


  /**
   * Sets the value of the 'patientId' field.
   * @param value the value to set.
   */
  public void setPatientId(long value) {
    this.patientId = value;
  }

  /**
   * Gets the value of the 'episodeOfCareId' field.
   * @return The value of the 'episodeOfCareId' field.
   */
  public long getEpisodeOfCareId() {
    return episodeOfCareId;
  }


  /**
   * Sets the value of the 'episodeOfCareId' field.
   * @param value the value to set.
   */
  public void setEpisodeOfCareId(long value) {
    this.episodeOfCareId = value;
  }

  /**
   * Gets the value of the 'wardId' field.
   * @return The value of the 'wardId' field.
   */
  public long getWardId() {
    return wardId;
  }


  /**
   * Sets the value of the 'wardId' field.
   * @param value the value to set.
   */
  public void setWardId(long value) {
    this.wardId = value;
  }

  /**
   * Gets the value of the 'roomId' field.
   * @return The value of the 'roomId' field.
   */
  public long getRoomId() {
    return roomId;
  }


  /**
   * Sets the value of the 'roomId' field.
   * @param value the value to set.
   */
  public void setRoomId(long value) {
    this.roomId = value;
  }

  /**
   * Gets the value of the 'bedId' field.
   * @return The value of the 'bedId' field.
   */
  public long getBedId() {
    return bedId;
  }


  /**
   * Sets the value of the 'bedId' field.
   * @param value the value to set.
   */
  public void setBedId(long value) {
    this.bedId = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return Encounter status
   */
  public ch.demo.gpietro.schema.EncounterStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * Encounter status
   * @param value the value to set.
   */
  public void setStatus(ch.demo.gpietro.schema.EncounterStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public java.time.Instant getDate() {
    return date;
  }


  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(java.time.Instant value) {
    this.date = value;
  }

  /**
   * Creates a new EventPatientLocation RecordBuilder.
   * @return A new EventPatientLocation RecordBuilder
   */
  public static ch.demo.gpietro.schema.EventPatientLocation.Builder newBuilder() {
    return new ch.demo.gpietro.schema.EventPatientLocation.Builder();
  }

  /**
   * Creates a new EventPatientLocation RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new EventPatientLocation RecordBuilder
   */
  public static ch.demo.gpietro.schema.EventPatientLocation.Builder newBuilder(ch.demo.gpietro.schema.EventPatientLocation.Builder other) {
    if (other == null) {
      return new ch.demo.gpietro.schema.EventPatientLocation.Builder();
    } else {
      return new ch.demo.gpietro.schema.EventPatientLocation.Builder(other);
    }
  }

  /**
   * Creates a new EventPatientLocation RecordBuilder by copying an existing EventPatientLocation instance.
   * @param other The existing instance to copy.
   * @return A new EventPatientLocation RecordBuilder
   */
  public static ch.demo.gpietro.schema.EventPatientLocation.Builder newBuilder(ch.demo.gpietro.schema.EventPatientLocation other) {
    if (other == null) {
      return new ch.demo.gpietro.schema.EventPatientLocation.Builder();
    } else {
      return new ch.demo.gpietro.schema.EventPatientLocation.Builder(other);
    }
  }

  /**
   * RecordBuilder for EventPatientLocation instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventPatientLocation>
    implements org.apache.avro.data.RecordBuilder<EventPatientLocation> {

    private long patientId;
    private long episodeOfCareId;
    private long wardId;
    private long roomId;
    private long bedId;
    /** Encounter status */
    private ch.demo.gpietro.schema.EncounterStatus status;
    private java.time.Instant date;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(ch.demo.gpietro.schema.EventPatientLocation.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.patientId)) {
        this.patientId = data().deepCopy(fields()[0].schema(), other.patientId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.episodeOfCareId)) {
        this.episodeOfCareId = data().deepCopy(fields()[1].schema(), other.episodeOfCareId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.wardId)) {
        this.wardId = data().deepCopy(fields()[2].schema(), other.wardId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.roomId)) {
        this.roomId = data().deepCopy(fields()[3].schema(), other.roomId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.bedId)) {
        this.bedId = data().deepCopy(fields()[4].schema(), other.bedId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.date)) {
        this.date = data().deepCopy(fields()[6].schema(), other.date);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing EventPatientLocation instance
     * @param other The existing instance to copy.
     */
    private Builder(ch.demo.gpietro.schema.EventPatientLocation other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.patientId)) {
        this.patientId = data().deepCopy(fields()[0].schema(), other.patientId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.episodeOfCareId)) {
        this.episodeOfCareId = data().deepCopy(fields()[1].schema(), other.episodeOfCareId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.wardId)) {
        this.wardId = data().deepCopy(fields()[2].schema(), other.wardId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.roomId)) {
        this.roomId = data().deepCopy(fields()[3].schema(), other.roomId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.bedId)) {
        this.bedId = data().deepCopy(fields()[4].schema(), other.bedId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.status)) {
        this.status = data().deepCopy(fields()[5].schema(), other.status);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.date)) {
        this.date = data().deepCopy(fields()[6].schema(), other.date);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'patientId' field.
      * @return The value.
      */
    public long getPatientId() {
      return patientId;
    }


    /**
      * Sets the value of the 'patientId' field.
      * @param value The value of 'patientId'.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder setPatientId(long value) {
      validate(fields()[0], value);
      this.patientId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'patientId' field has been set.
      * @return True if the 'patientId' field has been set, false otherwise.
      */
    public boolean hasPatientId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'patientId' field.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder clearPatientId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'episodeOfCareId' field.
      * @return The value.
      */
    public long getEpisodeOfCareId() {
      return episodeOfCareId;
    }


    /**
      * Sets the value of the 'episodeOfCareId' field.
      * @param value The value of 'episodeOfCareId'.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder setEpisodeOfCareId(long value) {
      validate(fields()[1], value);
      this.episodeOfCareId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'episodeOfCareId' field has been set.
      * @return True if the 'episodeOfCareId' field has been set, false otherwise.
      */
    public boolean hasEpisodeOfCareId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'episodeOfCareId' field.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder clearEpisodeOfCareId() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'wardId' field.
      * @return The value.
      */
    public long getWardId() {
      return wardId;
    }


    /**
      * Sets the value of the 'wardId' field.
      * @param value The value of 'wardId'.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder setWardId(long value) {
      validate(fields()[2], value);
      this.wardId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'wardId' field has been set.
      * @return True if the 'wardId' field has been set, false otherwise.
      */
    public boolean hasWardId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'wardId' field.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder clearWardId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'roomId' field.
      * @return The value.
      */
    public long getRoomId() {
      return roomId;
    }


    /**
      * Sets the value of the 'roomId' field.
      * @param value The value of 'roomId'.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder setRoomId(long value) {
      validate(fields()[3], value);
      this.roomId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'roomId' field has been set.
      * @return True if the 'roomId' field has been set, false otherwise.
      */
    public boolean hasRoomId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'roomId' field.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder clearRoomId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'bedId' field.
      * @return The value.
      */
    public long getBedId() {
      return bedId;
    }


    /**
      * Sets the value of the 'bedId' field.
      * @param value The value of 'bedId'.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder setBedId(long value) {
      validate(fields()[4], value);
      this.bedId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'bedId' field has been set.
      * @return True if the 'bedId' field has been set, false otherwise.
      */
    public boolean hasBedId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'bedId' field.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder clearBedId() {
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * Encounter status
      * @return The value.
      */
    public ch.demo.gpietro.schema.EncounterStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * Encounter status
      * @param value The value of 'status'.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder setStatus(ch.demo.gpietro.schema.EncounterStatus value) {
      validate(fields()[5], value);
      this.status = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * Encounter status
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'status' field.
      * Encounter status
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder clearStatus() {
      status = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public java.time.Instant getDate() {
      return date;
    }


    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder setDate(java.time.Instant value) {
      validate(fields()[6], value);
      this.date = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public ch.demo.gpietro.schema.EventPatientLocation.Builder clearDate() {
      date = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public EventPatientLocation build() {
      try {
        EventPatientLocation record = new EventPatientLocation();
        record.patientId = fieldSetFlags()[0] ? this.patientId : (java.lang.Long) defaultValue(fields()[0]);
        record.episodeOfCareId = fieldSetFlags()[1] ? this.episodeOfCareId : (java.lang.Long) defaultValue(fields()[1]);
        record.wardId = fieldSetFlags()[2] ? this.wardId : (java.lang.Long) defaultValue(fields()[2]);
        record.roomId = fieldSetFlags()[3] ? this.roomId : (java.lang.Long) defaultValue(fields()[3]);
        record.bedId = fieldSetFlags()[4] ? this.bedId : (java.lang.Long) defaultValue(fields()[4]);
        record.status = fieldSetFlags()[5] ? this.status : (ch.demo.gpietro.schema.EncounterStatus) defaultValue(fields()[5]);
        record.date = fieldSetFlags()[6] ? this.date : (java.time.Instant) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<EventPatientLocation>
    WRITER$ = (org.apache.avro.io.DatumWriter<EventPatientLocation>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<EventPatientLocation>
    READER$ = (org.apache.avro.io.DatumReader<EventPatientLocation>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










