/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package ch.demo.gpietro.schema.avro;
@org.apache.avro.specific.AvroGenerated
public enum EncounterStatus implements org.apache.avro.generic.GenericEnumSymbol<EncounterStatus> {
  PAST, ACTIVE, PLANNED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EncounterStatus\",\"namespace\":\"ch.demo.gpietro.schema.avro\",\"symbols\":[\"PAST\",\"ACTIVE\",\"PLANNED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
