/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package ch.demo.gpietro.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Encounter extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -8903062255579997251L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Encounter\",\"namespace\":\"ch.demo.gpietro.schema\",\"fields\":[{\"name\":\"encounterId\",\"type\":\"long\",\"doc\":\"Encounter id\"},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"EncounterStatus\",\"symbols\":[\"PLANNED\",\"ARRIVED\",\"TRIAGED\",\"INPROGRESS\",\"ONLEAVE\",\"FINISHED\",\"CANCELLED\"]},\"doc\":\"Encounter status\"},{\"name\":\"patientId\",\"type\":\"long\",\"doc\":\"Patient id\"}],\"version\":\"1\"}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<Encounter> ENCODER =
            new BinaryMessageEncoder<Encounter>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<Encounter> DECODER =
            new BinaryMessageDecoder<Encounter>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<Encounter> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<Encounter> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<Encounter> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<Encounter>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this Encounter to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a Encounter from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a Encounter instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static Encounter fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /** Encounter id */
    private long encounterId;
    /** Encounter status */
    private ch.demo.gpietro.schema.EncounterStatus status;
    /** Patient id */
    private long patientId;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public Encounter() {
    }

    /**
     * All-args constructor.
     * @param encounterId Encounter id
     * @param status Encounter status
     * @param patientId Patient id
     */
    public Encounter(java.lang.Long encounterId, ch.demo.gpietro.schema.EncounterStatus status, java.lang.Long patientId) {
        this.encounterId = encounterId;
        this.status = status;
        this.patientId = patientId;
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return encounterId;
            case 1:
                return status;
            case 2:
                return patientId;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                encounterId = (java.lang.Long) value$;
                break;
            case 1:
                status = (ch.demo.gpietro.schema.EncounterStatus) value$;
                break;
            case 2:
                patientId = (java.lang.Long) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'encounterId' field.
     * @return Encounter id
     */
    public long getEncounterId() {
        return encounterId;
    }


    /**
     * Sets the value of the 'encounterId' field.
     * Encounter id
     * @param value the value to set.
     */
    public void setEncounterId(long value) {
        this.encounterId = value;
    }

    /**
     * Gets the value of the 'status' field.
     * @return Encounter status
     */
    public ch.demo.gpietro.schema.EncounterStatus getStatus() {
        return status;
    }


    /**
     * Sets the value of the 'status' field.
     * Encounter status
     * @param value the value to set.
     */
    public void setStatus(ch.demo.gpietro.schema.EncounterStatus value) {
        this.status = value;
    }

    /**
     * Gets the value of the 'patientId' field.
     * @return Patient id
     */
    public long getPatientId() {
        return patientId;
    }


    /**
     * Sets the value of the 'patientId' field.
     * Patient id
     * @param value the value to set.
     */
    public void setPatientId(long value) {
        this.patientId = value;
    }

    /**
     * Creates a new Encounter RecordBuilder.
     * @return A new Encounter RecordBuilder
     */
    public static ch.demo.gpietro.schema.Encounter.Builder newBuilder() {
        return new ch.demo.gpietro.schema.Encounter.Builder();
    }

    /**
     * Creates a new Encounter RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new Encounter RecordBuilder
     */
    public static ch.demo.gpietro.schema.Encounter.Builder newBuilder(ch.demo.gpietro.schema.Encounter.Builder other) {
        if (other == null) {
            return new ch.demo.gpietro.schema.Encounter.Builder();
        } else {
            return new ch.demo.gpietro.schema.Encounter.Builder(other);
        }
    }

    /**
     * Creates a new Encounter RecordBuilder by copying an existing Encounter instance.
     * @param other The existing instance to copy.
     * @return A new Encounter RecordBuilder
     */
    public static ch.demo.gpietro.schema.Encounter.Builder newBuilder(ch.demo.gpietro.schema.Encounter other) {
        if (other == null) {
            return new ch.demo.gpietro.schema.Encounter.Builder();
        } else {
            return new ch.demo.gpietro.schema.Encounter.Builder(other);
        }
    }

    /**
     * RecordBuilder for Encounter instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Encounter>
            implements org.apache.avro.data.RecordBuilder<Encounter> {

        /** Encounter id */
        private long encounterId;
        /** Encounter status */
        private ch.demo.gpietro.schema.EncounterStatus status;
        /** Patient id */
        private long patientId;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(ch.demo.gpietro.schema.Encounter.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.encounterId)) {
                this.encounterId = data().deepCopy(fields()[0].schema(), other.encounterId);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.status)) {
                this.status = data().deepCopy(fields()[1].schema(), other.status);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.patientId)) {
                this.patientId = data().deepCopy(fields()[2].schema(), other.patientId);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
        }

        /**
         * Creates a Builder by copying an existing Encounter instance
         * @param other The existing instance to copy.
         */
        private Builder(ch.demo.gpietro.schema.Encounter other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.encounterId)) {
                this.encounterId = data().deepCopy(fields()[0].schema(), other.encounterId);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.status)) {
                this.status = data().deepCopy(fields()[1].schema(), other.status);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.patientId)) {
                this.patientId = data().deepCopy(fields()[2].schema(), other.patientId);
                fieldSetFlags()[2] = true;
            }
        }

        /**
         * Gets the value of the 'encounterId' field.
         * Encounter id
         * @return The value.
         */
        public long getEncounterId() {
            return encounterId;
        }


        /**
         * Sets the value of the 'encounterId' field.
         * Encounter id
         * @param value The value of 'encounterId'.
         * @return This builder.
         */
        public ch.demo.gpietro.schema.Encounter.Builder setEncounterId(long value) {
            validate(fields()[0], value);
            this.encounterId = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'encounterId' field has been set.
         * Encounter id
         * @return True if the 'encounterId' field has been set, false otherwise.
         */
        public boolean hasEncounterId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'encounterId' field.
         * Encounter id
         * @return This builder.
         */
        public ch.demo.gpietro.schema.Encounter.Builder clearEncounterId() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'status' field.
         * Encounter status
         * @return The value.
         */
        public ch.demo.gpietro.schema.EncounterStatus getStatus() {
            return status;
        }


        /**
         * Sets the value of the 'status' field.
         * Encounter status
         * @param value The value of 'status'.
         * @return This builder.
         */
        public ch.demo.gpietro.schema.Encounter.Builder setStatus(ch.demo.gpietro.schema.EncounterStatus value) {
            validate(fields()[1], value);
            this.status = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'status' field has been set.
         * Encounter status
         * @return True if the 'status' field has been set, false otherwise.
         */
        public boolean hasStatus() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'status' field.
         * Encounter status
         * @return This builder.
         */
        public ch.demo.gpietro.schema.Encounter.Builder clearStatus() {
            status = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'patientId' field.
         * Patient id
         * @return The value.
         */
        public long getPatientId() {
            return patientId;
        }


        /**
         * Sets the value of the 'patientId' field.
         * Patient id
         * @param value The value of 'patientId'.
         * @return This builder.
         */
        public ch.demo.gpietro.schema.Encounter.Builder setPatientId(long value) {
            validate(fields()[2], value);
            this.patientId = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'patientId' field has been set.
         * Patient id
         * @return True if the 'patientId' field has been set, false otherwise.
         */
        public boolean hasPatientId() {
            return fieldSetFlags()[2];
        }


        /**
         * Clears the value of the 'patientId' field.
         * Patient id
         * @return This builder.
         */
        public ch.demo.gpietro.schema.Encounter.Builder clearPatientId() {
            fieldSetFlags()[2] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public Encounter build() {
            try {
                Encounter record = new Encounter();
                record.encounterId = fieldSetFlags()[0] ? this.encounterId : (java.lang.Long) defaultValue(fields()[0]);
                record.status = fieldSetFlags()[1] ? this.status : (ch.demo.gpietro.schema.EncounterStatus) defaultValue(fields()[1]);
                record.patientId = fieldSetFlags()[2] ? this.patientId : (java.lang.Long) defaultValue(fields()[2]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<Encounter>
            WRITER$ = (org.apache.avro.io.DatumWriter<Encounter>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<Encounter>
            READER$ = (org.apache.avro.io.DatumReader<Encounter>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeLong(this.encounterId);

        out.writeEnum(this.status.ordinal());

        out.writeLong(this.patientId);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.encounterId = in.readLong();

            this.status = ch.demo.gpietro.schema.EncounterStatus.values()[in.readEnum()];

            this.patientId = in.readLong();

        } else {
            for (int i = 0; i < 3; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.encounterId = in.readLong();
                        break;

                    case 1:
                        this.status = ch.demo.gpietro.schema.EncounterStatus.values()[in.readEnum()];
                        break;

                    case 2:
                        this.patientId = in.readLong();
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}










