/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package ch.demo.gpietro.schema;

@org.apache.avro.specific.AvroGenerated
public enum EncounterStatus implements org.apache.avro.generic.GenericEnumSymbol<EncounterStatus> {
    PLANNED, ARRIVED, TRIAGED, INPROGRESS, ONLEAVE, FINISHED, CANCELLED;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"EncounterStatus\",\"namespace\":\"ch.demo.gpietro.schema\",\"symbols\":[\"PLANNED\",\"ARRIVED\",\"TRIAGED\",\"INPROGRESS\",\"ONLEAVE\",\"FINISHED\",\"CANCELLED\"]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }
}
