/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package ch.demo.gpietro.schema;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class EventPatientCheckedOut extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -4450011687889572524L;
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"EventPatientCheckedOut\",\"namespace\":\"ch.demo.gpietro.schema\",\"fields\":[{\"name\":\"patientId\",\"type\":\"long\"},{\"name\":\"treatmentId\",\"type\":\"long\"}],\"version\":\"1\"}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<EventPatientCheckedOut> ENCODER =
            new BinaryMessageEncoder<EventPatientCheckedOut>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<EventPatientCheckedOut> DECODER =
            new BinaryMessageDecoder<EventPatientCheckedOut>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<EventPatientCheckedOut> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<EventPatientCheckedOut> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<EventPatientCheckedOut> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<EventPatientCheckedOut>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this EventPatientCheckedOut to a ByteBuffer.
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a EventPatientCheckedOut from a ByteBuffer.
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a EventPatientCheckedOut instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static EventPatientCheckedOut fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private long patientId;
    private long treatmentId;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public EventPatientCheckedOut() {
    }

    /**
     * All-args constructor.
     * @param patientId The new value for patientId
     * @param treatmentId The new value for treatmentId
     */
    public EventPatientCheckedOut(java.lang.Long patientId, java.lang.Long treatmentId) {
        this.patientId = patientId;
        this.treatmentId = treatmentId;
    }

    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return patientId;
            case 1:
                return treatmentId;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                patientId = (java.lang.Long) value$;
                break;
            case 1:
                treatmentId = (java.lang.Long) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'patientId' field.
     * @return The value of the 'patientId' field.
     */
    public long getPatientId() {
        return patientId;
    }


    /**
     * Sets the value of the 'patientId' field.
     * @param value the value to set.
     */
    public void setPatientId(long value) {
        this.patientId = value;
    }

    /**
     * Gets the value of the 'treatmentId' field.
     * @return The value of the 'treatmentId' field.
     */
    public long getTreatmentId() {
        return treatmentId;
    }


    /**
     * Sets the value of the 'treatmentId' field.
     * @param value the value to set.
     */
    public void setTreatmentId(long value) {
        this.treatmentId = value;
    }

    /**
     * Creates a new EventPatientCheckedOut RecordBuilder.
     * @return A new EventPatientCheckedOut RecordBuilder
     */
    public static ch.demo.gpietro.schema.EventPatientCheckedOut.Builder newBuilder() {
        return new ch.demo.gpietro.schema.EventPatientCheckedOut.Builder();
    }

    /**
     * Creates a new EventPatientCheckedOut RecordBuilder by copying an existing Builder.
     * @param other The existing builder to copy.
     * @return A new EventPatientCheckedOut RecordBuilder
     */
    public static ch.demo.gpietro.schema.EventPatientCheckedOut.Builder newBuilder(ch.demo.gpietro.schema.EventPatientCheckedOut.Builder other) {
        if (other == null) {
            return new ch.demo.gpietro.schema.EventPatientCheckedOut.Builder();
        } else {
            return new ch.demo.gpietro.schema.EventPatientCheckedOut.Builder(other);
        }
    }

    /**
     * Creates a new EventPatientCheckedOut RecordBuilder by copying an existing EventPatientCheckedOut instance.
     * @param other The existing instance to copy.
     * @return A new EventPatientCheckedOut RecordBuilder
     */
    public static ch.demo.gpietro.schema.EventPatientCheckedOut.Builder newBuilder(ch.demo.gpietro.schema.EventPatientCheckedOut other) {
        if (other == null) {
            return new ch.demo.gpietro.schema.EventPatientCheckedOut.Builder();
        } else {
            return new ch.demo.gpietro.schema.EventPatientCheckedOut.Builder(other);
        }
    }

    /**
     * RecordBuilder for EventPatientCheckedOut instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<EventPatientCheckedOut>
            implements org.apache.avro.data.RecordBuilder<EventPatientCheckedOut> {

        private long patientId;
        private long treatmentId;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         * @param other The existing Builder to copy.
         */
        private Builder(ch.demo.gpietro.schema.EventPatientCheckedOut.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.patientId)) {
                this.patientId = data().deepCopy(fields()[0].schema(), other.patientId);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.treatmentId)) {
                this.treatmentId = data().deepCopy(fields()[1].schema(), other.treatmentId);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
        }

        /**
         * Creates a Builder by copying an existing EventPatientCheckedOut instance
         * @param other The existing instance to copy.
         */
        private Builder(ch.demo.gpietro.schema.EventPatientCheckedOut other) {
            super(SCHEMA$);
            if (isValidValue(fields()[0], other.patientId)) {
                this.patientId = data().deepCopy(fields()[0].schema(), other.patientId);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.treatmentId)) {
                this.treatmentId = data().deepCopy(fields()[1].schema(), other.treatmentId);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'patientId' field.
         * @return The value.
         */
        public long getPatientId() {
            return patientId;
        }


        /**
         * Sets the value of the 'patientId' field.
         * @param value The value of 'patientId'.
         * @return This builder.
         */
        public ch.demo.gpietro.schema.EventPatientCheckedOut.Builder setPatientId(long value) {
            validate(fields()[0], value);
            this.patientId = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'patientId' field has been set.
         * @return True if the 'patientId' field has been set, false otherwise.
         */
        public boolean hasPatientId() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'patientId' field.
         * @return This builder.
         */
        public ch.demo.gpietro.schema.EventPatientCheckedOut.Builder clearPatientId() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'treatmentId' field.
         * @return The value.
         */
        public long getTreatmentId() {
            return treatmentId;
        }


        /**
         * Sets the value of the 'treatmentId' field.
         * @param value The value of 'treatmentId'.
         * @return This builder.
         */
        public ch.demo.gpietro.schema.EventPatientCheckedOut.Builder setTreatmentId(long value) {
            validate(fields()[1], value);
            this.treatmentId = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'treatmentId' field has been set.
         * @return True if the 'treatmentId' field has been set, false otherwise.
         */
        public boolean hasTreatmentId() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'treatmentId' field.
         * @return This builder.
         */
        public ch.demo.gpietro.schema.EventPatientCheckedOut.Builder clearTreatmentId() {
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public EventPatientCheckedOut build() {
            try {
                EventPatientCheckedOut record = new EventPatientCheckedOut();
                record.patientId = fieldSetFlags()[0] ? this.patientId : (java.lang.Long) defaultValue(fields()[0]);
                record.treatmentId = fieldSetFlags()[1] ? this.treatmentId : (java.lang.Long) defaultValue(fields()[1]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<EventPatientCheckedOut>
            WRITER$ = (org.apache.avro.io.DatumWriter<EventPatientCheckedOut>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<EventPatientCheckedOut>
            READER$ = (org.apache.avro.io.DatumReader<EventPatientCheckedOut>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeLong(this.patientId);

        out.writeLong(this.treatmentId);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.patientId = in.readLong();

            this.treatmentId = in.readLong();

        } else {
            for (int i = 0; i < 2; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.patientId = in.readLong();
                        break;

                    case 1:
                        this.treatmentId = in.readLong();
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}










