server:
  port: 9999
spring:
  application:
    name: patient-streams
  cloud:
    stream:
      bindings:
        process-in-0:
          destination: mysql.admindb.patients
          group: storeStreamsGroup
          consumer:
            useNativeDecoding: true
#        process-out-0:
#          destination: store.streams.patients
#          producer:
#            useNativeEncoding: true
      kafka:
        streams:
          binder:
            configuration:
              schema.registry.url: http://${SCHEMA_REGISTRY_HOST:localhost}:${SCHEMA_REGISTRY_PORT:8081}
          bindings:
            process-in-0:
              patient:
                keySerde: org.apache.kafka.common.serialization.Serdes$LongSerde
                valueSerde: ch.demo.gpietro.serde.PatientAvroSerde